### ISSUE TITLE
Use ButterKnife to reduce Boilerplate Code

### ISSUE THREAD

**Issue by PramUkesh** [KYHSGeekCode/Android-Disassembler#20]
Use ButterKnife lib to reduce code at present code looking clumsy 
and use separate method if nested methods are way long your code nesting very deep 
I think you are using mobile to build it 
how can build such deep nested classes with mobile
avoiding deep nesting improves readability of code

if you are interested and have resources try kotlin lang which is much more advanced and modern language with minimal syntax most of functions in in built to it and some of best are extension function

by the way what is your school standard

**Comment by KYHSGeekCode** [comment]
I tried utilizing the Butterknife in an other project, but I failed because AIDE currently doesn't support annotation processing. However I, either am thinking about organizing the long long code of MainActivity. Thanks for your suggestion. Luckily AIDE supports nested classes. I tried learning Kotlin Lang to follow up the  latest current, but maybe I will be able to use it after CSAT. By now I am just an admirer of Kotlin Developers. And by now there's no Kotlin compiler on mobile I guess, so I am planning to make one. Or I may not need it as I may develop on desktop after CSAT.

By the way what do you mean by School standard?

1. My academic status = High school student, preparing for university enterance(CSAT is for that)
2. My school's standard programming language = none, as my school does not teach programming for Science-intense classes to teach some foreign languages for students who wants to enter Seoul ntional University(At least some amount of class attendence times are needed to enter there)

**Comment by PramUkesh** [comment]
Same as me I learn coding myself watch free videos

**Comment by PramUkesh** [comment]
Also I was currently testing flutter

**Comment by KYHSGeekCode** [comment]
What is flutter?

**Comment by PramUkesh** [comment]
Flutter is new way to build android and iOS apps with single code base it uses modern language dart and flutter framework built by google its same code is used for fuchsia OS in future read wiki for more about fuchsia, flutter,dart

**Comment by KYHSGeekCode** [comment]
Fantastic!

**Comment by KYHSGeekCode** [comment]
https://github.com/tranleduy2000/javaide/issues/126 Kotlin IDEvon android seems a far far long way to go. I may develop on Kotlin or flutter after CSAT.

**Comment by KYHSGeekCode** [comment]
> if you are interested and have resources try kotlin lang which is much more advanced and modern language with minimal syntax most of functions in in built to it and some of best are extension function

Currently kotlin is now aggressively used in this project.
